apiVersion: v1
kind: Service
metadata:
  name: {{ include "solana.fullname" . }}
  labels:
    {{- include "solana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "solana.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "solana.fullname" . }}-p2p
  labels:
    {{- include "solana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceP2P.type }}
  ports:
    - port: {{ .Values.container.ports.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
      nodePort: {{ .Values.container.ports.rpc }}
    - port: {{ .Values.container.ports.gossip }}
      targetPort: gossip-tcp
      protocol: TCP
      name: gossip-tcp
      nodePort: {{ .Values.container.ports.gossip }}
    - port: {{ .Values.container.ports.gossip }}
      targetPort: gossip-udp
      protocol: UDP
      name: gossip-udp
      nodePort: {{ .Values.container.ports.gossip }}
    {{- range .Values.container.ports.listener }}
    - port: {{ . }}
      targetPort: {{ . }} 
      protocol: UDP
      name: listener-{{ . }}
      nodePort: {{ . }}
    {{- end }}
  selector:
    {{- include "solana.selectorLabels" . | nindent 4 }}